name: cupertino_ffi
version: 0.2.2
description:
  This package enables Dart developers to use various C APIs by Apple (Core Foundation, Security,
  etc.).
homepage: https://github.com/dart-interop/cupertino_ffi

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  ffi: ^0.1.3
  meta: ^1.1.0

dev_dependencies:
  cupertino_ffi_generated: any
  ffi_tool: ^0.2.2
  pedantic: ^1.9.0
  test: ^1.6.0